title: JJuergens Development Site
description: For a Masters of Science in Business Analytics student at the College of William & Mary
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
